### ISSUE TITLE
How to set up FAS

### ISSUE THREAD

**Issue by weili71** [openNDS/openNDS#115]
How to set up FAS and connect to remote server example.com , I modify the configuration file according to the document, but it doesn't work after restart, it doesn't access example.com , also does not provide mandatory portal page, can you give an example

**Comment by bluewavenet** [comment]
@weili71 
The relevant part of the documentation is here:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas
with examples here:
https://opennds.readthedocs.io/en/stable/fas.html#using-the-fas-example-scripts-fas-hid-fas-aes-php-and-fas-aes-https-php

If you have read these and are still having problems, please post the output of:
`ndsctl status`
and
`uci show opennds`

**Comment by weili71** [comment]
$ ndsctl status
ndsctl: opennds probably not started (Error: Connection refused)
# root @ OpenWrt in ~ [17:50:26]
$ uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fasport='4430'
opennds.@opennds[0].faspath='/nds/fas-hid.php'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fasremotefqdn='xyzcom.xyz'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].gatewayfqdn='status.client'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].authenticated_users='allow all'opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'

**Comment by bluewavenet** [comment]
@weili71 
You have a number of things wrong here.
OpenNDS is failing to start.
If you run:
`service opennds restart`
followed by
`logread | grep "opennds"`

then you should get an indication of the problem.

Have you installed php7-cli and php7-mod-openssl? These are required for fas_secure_enabled levels 2 and 3.
Note also that fas-hid.php requires fas_secure_enabled level 1. If you set this to 1, then openNDS will most likely start.

**Comment by weili71** [comment]
Thanks for your help, I have found out the error: php7-cli and php7-mod-openssl are not installed, now openNDS is working normally

**Comment by bluewavenet** [comment]
@weili71 
As you are set at fas_secure_enabled level 3, I assume you also changed from fas-hid to fas-aes-https?

**Comment by weili71** [comment]
I did not write FAS in php, but in golang

**Comment by weili71** [comment]
How to use only https without aes-cbc-256 encryption, because some programming languages ​​are difficult to decrypt; is there a fas api document, because for me the php language is really difficult to understand

**Comment by sicelo** [comment]
It seems not. However, Go, as a modern language, should support aes-cbc-256 very well. A quick search on the internet brought up these examples,

https://gist.github.com/yingray/57fdc3264b1927ef0f984b533d63abab
https://medium.com/@thanat.arp/encrypt-decrypt-aes256-cbc-shell-script-golang-node-js-ffb675a05669

Also this wrapper could potentially help, https://pkg.go.dev/github.com/spacemonkeygo/openssl

At the worst, you could even call openssl straight from the shell using your implementation of FAS

**Comment by weili71** [comment]
I still hope to provide a fas_secure_enabled=‘4’ option, which only forces https on the basis of ‘1’

**Comment by weili71** [comment]
What to do after fas authentication is successful, I don’t understand the documentation, and I don’t understand the php example

**Comment by sicelo** [comment]
Still the fas option 3?

https://opennds.readthedocs.io/en/stable/fas.html#authentication-method-for-fas-secure-enabled-level-3-authmon-daemon

**Comment by bluewavenet** [comment]
@weili71 
For clarity, consider using this terminology:
 * FAS gets the client credentials and verifies them in some way - we call this **"Validation"**
 * FAS then makes a request to openNDS to allow the client to access the Internet - we call this **"Authentication"**
 

> What to do after fas [validation] is successful

OpenNDS runs the authmon daemon. This polls the remote FAS so that FAS can send its client authentication request.

Authmon does a POST request from the remote FAS.
Here is the php code from fas-aes-https:
```
#############################################################################################################
#
# Send The Auth List when requested by openNDS
#
# When a client was verified, their parameters were added to the "auth list"
# The auth list is sent to NDS when it requests it.
#
# auth_get:
# value "list" sends the list and deletes each client entry that it finds
# value "view" just sends the list (useful only for debugging)
#
#############################################################################################################

if (isset($_POST["auth_get"])) {

	if (isset($_POST["gatewayhash"])) {
		$gatewayhash=$_POST["gatewayhash"];
	} else {
		exit(0);
	}

	if (! file_exists("$gatewayhash")) {
		exit(0);
	}

	$authlist="*";

	if ($_POST["auth_get"] == "list") {
		$auth_list=scandir("$gatewayhash");
		array_shift($auth_list);
		array_shift($auth_list);

		foreach ($auth_list as $client) {
			$clientauth=file("$gatewayhash/$client");
			$authlist=$authlist." ".rawurlencode(trim($clientauth[0]));
			unlink("$gatewayhash/$client");
		}
		echo trim("$authlist");

	} else if ($_POST["auth_get"] == "view") {
		$auth_list=scandir("$gatewayhash");
		array_shift($auth_list);
		array_shift($auth_list);

		foreach ($auth_list as $client) {
			$clientauth=file("$gatewayhash/$client");
			$authlist=$authlist." ".rawurlencode(trim($clientauth[0]));
		}
		echo trim("$authlist");
	}
	exit(0);
}
#############################################################################################################

```

Authmon sends gatewayhash, a hashed version of gatewayname, for identification, along with auth_get, a request for a list of data containing details of clients to authenticate. This data is held in a data file.

FAS of course creates the list file.
I will post next the php that creates entries in the data file.

**Comment by bluewavenet** [comment]
@weili71 

> aes-cbc-256 encryption

There seem to be numerous examples of aes encryption/decryption for Golang - you just need to search.

**Comment by weili71** [comment]
> * FAS then makes a request to openNDS to allow the client to access the Internet - we call this **"Authentication"**

How to access openNDS under NAT？

**Comment by bluewavenet** [comment]
The OpenNDS Authmon daemon briefly opens a nat traversal channel by polling the remote FAS allowing FAS to send to OpenNDS behind nat.

**Comment by bluewavenet** [comment]
@weili71 
I am sure you can use Golang to write your FAS, but I would suggest initially setting up fas-aes-https.php 
Then you will be confident your openNDS configuration is correct and get a good understanding of how it works before moving on to re-coding into Golang.

**Comment by bluewavenet** [comment]
@weili71 

> I still hope to provide a fas_secure_enabled=‘4’ option, which only forces https on the basis of ‘1’

You will still need to use authmon nat traversal, otherwise clients will get a TLS security warning at the "Authentication" stage.
The only advantage is that you would not need to decrypt at the FAS end. With lots of code snippets/libraries etc for decrypting, in my opinion, it is hardly worth the effort providing an option that is less secure.

**Comment by bluewavenet** [comment]
@weili71 
If you have any further questions on this subject please post here or open a new issue for a new subject.

**Comment by martinord** [comment]
@bluewavenet 
Hi! I've reading through all this. In my case, I'm implementing a FAS server in NodeJS.

The thing is that I do not see when Authmon sends the POST request to the `/auth_get` endpoint. 

I have set up my own environment. OpenNDS is redirecting properly to the FAS server, and it is correctly sending the fas parameters. However, I am not yet receiving any POST request to the aforementioned endpoint from Authmon. Is there any way I can force OpenNDS to send this request?

Thanks

**Comment by bluewavenet** [comment]
@martinord 
Please open a new issue for this - titled for example "How do I communicate with Authmon from a remote https NodeJS server?"

**Comment by martinord** [comment]
Done! #212

**Comment by louatiMahmoudAziz** [comment]
Hello !
I hope you're all doing well. I am currently facing an issue while trying to configure FAS so that on my local Apache server in my pc  which is connected to the local network of the router on which the openNDS is installed  and I'm seeking some guidance to resolve it.

Problem Description:
My goal is to test FAS on a server that is connected to my router's local network. I've followed the OpenNDS documentation and set the relevant configuration options, but I'm encountering difficulties in making it work as expected.

My Configuration:

Apache Server Listening on Port 80
System File Path of fas-aes.php: C:\xampp\htdocs\nds\fas-aes.php
FAS Configuration Options in OpenNDS:
option fasport '80'
option faspath '/nds/fas-aes.php'
option fasremoteip '192.168.1.194' (my machine ip adress)
option faskey '1234567890'
option fas_secure_enabled '2'

I wonder if there's something I might be missing either in my OpenNDS configuration or possibly in my Apache server setup. 
I want to express my gratitude to the OpenNDS documentation. Thank you for your time and consideration. I'm hopeful for a positive resolution to this issue.

**Comment by bluewavenet** [comment]
@louatiMahmoudAziz 
You don't say what  your router hardware and operating system are and also you do not state the openNDS version.

The current version of opennDS is v10.1.2 and I strongly suggest you use this.

If you are on v10.1.2 then you have a config option missing.
You need to add:
`option fasremotefqdn 'disabled'`

Perhaps this is missing in the documentation, I will have to check.....

**Comment by bluewavenet** [comment]
@louatiMahmoudAziz 
As long as you are running v10.1.2 then yes you need to add the config option as I indicated. I will repeat it:
`option fasremotefqdn 'disabled'`

It seems the documentation is not clear. True it is not set by default but for a remote FAS you have to either set a valid `fasremotefqdn` or set it to `disabled`.

**Comment by louatiMahmoudAziz** [comment]
Sorry I forgot to mention the version I am using it is  v10.1.1 Now I found out that I misconfigured some options and when I corrected them it seems to be triggered
<img width="574" alt="Capture d’écran 2023-08-11 163508" src="https://github.com/openNDS/openNDS/assets/122715917/2a09fe7f-d661-41ac-b5d9-8201c14ef49a">
but I still have a problem and when I did logread I grep "opennds" I obtained this:
<img width="684" alt="Capture d’écran 2023-08-11 164600" src="https://github.com/openNDS/openNDS/assets/122715917/03710813-03dd-4bc6-8daa-c6f6aa4f63f7">
<img width="662" alt="Capture d’écran 2023-08-11 164425" src="https://github.com/openNDS/openNDS/assets/122715917/3063f559-3eca-4892-8a9c-f7edecc11e80">
Now I will try correcting the fqdn option

**Comment by bluewavenet** [comment]
@louatiMahmoudAziz 
As I stated before:

> The current version of openNDS is v10.1.2 and I strongly suggest you use this.

I will restate this - You **_MUST_** use v10.1.2

If you are using a generic Linux you can compile in place. If you are using OpenNDS you can download it.

**Please state the router hardware and the operating system/version.**

Once I know this information I can show you what to do.
